version: '2'

services:
  telegram-bot:
    image: tvgtu/telegram-bot:latest
    restart: always
    depends_on:
      - "telegram-db"
    environment:
      TELEGRAM_BOT_TOKEN:
      TELEGRAM_BOT_USERNAME:
      TELEGRAM_BOT_PAYMENT_TOKEN:
    networks:
      tstu_telegram_bot_network:
        ipv4_address: 172.36.0.2

  telegram-db:
    extends:
      file: postgresql.yml
      service: telegram-db

#  telegram-db:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_USER: telebot
#      POSTGRES_PASSWORD: 123456
#    networks:
#      tstu_telegram_bot_network:
#        ipv4_address: 172.36.0.3

  telegram-admin:
      image: tvgtu/telegram-bot-admin:snapshot-0.0.1
      restart: always
      depends_on:
        - "telegram-db"
        - "telegram-bot"
      ports:
        - 8090:8090
      networks:
        tstu_telegram_bot_network:
          ipv4_address: 172.36.0.4

networks:
  tstu_telegram_bot_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.36.0.0/16
          gateway: 172.36.0.1
