version: '2'
services:
  telegram-db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    volumes:
      - /tmp/omnibots/data/postgresql/:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: telebot
      POSTGRES_PASSWORD: 123456
    networks:
      tstu_telegram_bot_network:
        ipv4_address: 172.36.0.3

networks:
  tstu_telegram_bot_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.36.0.0/16
          gateway: 172.36.0.1